name: ci

on:
  push:
    branches:
      - main
      - develop
      - issues/*
  pull_request:
    branches:
      - main
      - develop
      - issues/*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Format check
      run: gofmt -w . && git diff --exit-code
    - name: Build
      run: go build -v -o a.out
    - name: Test
      run: go test -v
