name: ci

on:
  push:
    branches:
      - main
      - develop
      - issues/*
  pull_request:
    branches:
      - main
      - develop
      - issues/*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: GOPATH setting
      run: |
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$PATH
    - name: Format check
      run: gofmt -w . && git diff --exit-code
    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.3"
        install-go: false
    - name: Run go vet
      run: go vet ./...
    - name: Run goimports
      run: go install golang.org/x/tools/cmd/goimports@v0.12.0 && goimports -w . && git diff --exit-code
    - name: Build
      run: go build -v -o a.out
    - name: Test
      run: go test -v ./...
